coslr: true
criterions:
  PerformanceLoss:
    def_file: ./loss/GRWLoss.py
    loss_params: {exp_scale: 1.2, num_classes: 8142, freq_path: ./cls_freq/iNaturalist18.json}
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
memory: {centroids: false, init_centroids: false}
model_dir: ./logs/iNaturalist18/models/resnet50_uniform_e90
networks:
  classifier:
    def_file: ./models/MARCClassifier.py
    optim_params: {lr: 0.05, momentum: 0.9, weight_decay: 0.0001}
    params: {feat_dim: 2048, num_classes: 8142, stage1_weights: True, cls_freq: ./cls_freq/iNaturalist18.json, model_dir: ./logs/iNaturalist18/models/resnet50_uniform_e90}
  feat_model:
    def_file: ./models/ResNet50Feature.py
    fix: true
    optim_params: {lr: 0.05, momentum: 0.9, weight_decay: 0.0001}
    params: {dataset: iNaturalist18, dropout: null, stage1_weights: false,
      use_fc: false, use_selfatt: false}
shuffle: true
training_opt:
  batch_size: 256
  dataset: iNaturalist18
  display_step: 10
  feature_dim: 2048
  log_dir: ./logs/iNaturalist18/models/MARC
  log_root: ./logs/iNaturalist18
  num_classes: 8142
  num_epochs: 30
  num_workers: 4
  open_threshold: 0.1
  sampler: null
  scheduler_params: {gamma: 0.1, step_size: 30}
  stage: MARC
  sub_dir: models
